(()=>{'use strict';
const DAYS=['Mo','Di','Mi','Do','Fr'],FULL=['Montag','Dienstag','Mittwoch','Donnerstag','Freitag'];
const PEOPLE=[{id:'max',name:'Max',pos:"Max'"},{id:'matilda',name:'Matilda',pos:'Matildas'}];
const DEFAULTS=[{id:'vesper',emoji:'🥪',label:'Vesperdose + Trinkflasche ausgeräumt',people:['max','matilda'],days:[0,1,2,3,4]},{id:'homework',emoji:'✏️',label:'Hausaufgaben erledigt',people:['max','matilda'],days:[0,1,2,3,4]},{id:'bag',emoji:'🎒',label:'Schulranzen gepackt',people:['max','matilda'],days:[0,1,2,3,4]}];
const SETTINGS='mm-v2-settings',PREFIX='mm-v2-week-',now=new Date(),monday=getMonday(now),weekKey=dateKey(monday),storageKey=PREFIX+weekKey,weekday=now.getDay();
const DIRTY='mm-cloud-dirty',REVISION='mm-cloud-revision';
let selected=weekday>=1&&weekday<=5?weekday-1:0,settings=loadSettings(),state=loadWeek(),pending=null,draft=[],cloudRevision=0,cloudTimer=null,syncing=false,loadingCloud=false;
function getMonday(date){const d=new Date(date.getFullYear(),date.getMonth(),date.getDate()),n=d.getDay();d.setDate(d.getDate()-(n===0?6:n-1));d.setHours(0,0,0,0);return d}
function dateKey(d){return[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function clone(v){return JSON.parse(JSON.stringify(v))}
function loadSettings(){try{const s=JSON.parse(localStorage.getItem(SETTINGS));if(s?.tasks?.length)return{...s,target:Number(s.target)||4}}catch{}return{reward:'',target:4,tasks:clone(DEFAULTS)}}
function blank(){return{version:2,created:new Date().toISOString(),taskSnapshot:clone(settings.tasks),checks:{max:{},matilda:{}}}}
function loadWeek(){try{const d=JSON.parse(localStorage.getItem(storageKey));if(d?.version===2){d.taskSnapshot??=clone(settings.tasks);return d}}catch{}const fresh=blank();try{const old=JSON.parse(localStorage.getItem(`max-matilda-tasks-${weekKey}`));PEOPLE.forEach(p=>old?.[p.id]?.forEach((checks,day)=>checks.forEach((value,i)=>{if(value&&DEFAULTS[i])fresh.checks[p.id][`${day}:${DEFAULTS[i].id}`]=true})))}catch{}return fresh}
function relevant(person,day){return settings.tasks.filter(t=>t.people.includes(person)&&t.days.includes(day))}
function checked(person,day,id){return!!state.checks[person]?.[`${day}:${id}`]}
function setChecked(person,day,id,value){state.checks[person]??={};state.checks[person][`${day}:${id}`]=value}
function complete(person,day,data=state,taskList=data.taskSnapshot||settings.tasks){const tasks=taskList.filter(t=>t.people.includes(person)&&t.days.includes(day));return tasks.length>0&&tasks.every(t=>data.checks?.[person]?.[`${day}:${t.id}`])}
function stars(person,data=state,taskList=data.taskSnapshot||settings.tasks){return DAYS.filter((_,i)=>complete(person,i,data,taskList)).length}
function save(){localStorage.setItem(storageKey,JSON.stringify(state));localStorage.setItem(DIRTY,'1');setStatus(navigator.onLine?'Wird online gespeichert …':'Offline gespeichert');queueCloud()}
function setStatus(text){$('#save-status').textContent=text}
function showLogin(message=''){const dialog=$('#login-dialog');$('#login-error').textContent=message;if(!dialog.open)dialog.showModal();setStatus('Anmeldung erforderlich')}
async function ensureSession(){try{const response=await fetch('/api/auth');if(!response.ok){showLogin();return}if($('#login-dialog').open)$('#login-dialog').close();syncFromCloud()}catch{setStatus('Offline – lokaler Stand verfügbar')}}
function collectDocument(){const weeks={};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith(PREFIX)){try{weeks[key]=JSON.parse(localStorage.getItem(key))}catch{}}}return{version:2,settings,weeks}}
function applyDocument(doc){if(!doc?.settings||!doc?.weeks)return;for(let i=localStorage.length-1;i>=0;i--){const key=localStorage.key(i);if(key?.startsWith(PREFIX))localStorage.removeItem(key)}localStorage.setItem(SETTINGS,JSON.stringify(doc.settings));Object.entries(doc.weeks).forEach(([key,value])=>localStorage.setItem(key,JSON.stringify(value)));settings=loadSettings();state=loadWeek();render()}
function queueCloud(){clearTimeout(cloudTimer);cloudTimer=setTimeout(pushCloud,350)}
async function pushCloud(){if(syncing)return;syncing=true;try{const response=await fetch('/api/family-state',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({baseRevision:cloudRevision,document:collectDocument()})});if(response.status===401){showLogin('Bitte erneut anmelden.');return}const data=await response.json();if(response.status===409){setStatus('⚠ Neuerer Online-Stand vorhanden');return}if(!response.ok)throw Error();cloudRevision=data.revision;localStorage.setItem(REVISION,String(cloudRevision));localStorage.removeItem(DIRTY);setStatus('✓ Online gespeichert')}catch{setStatus('Offline gespeichert – Synchronisierung folgt')}finally{syncing=false}}
async function syncFromCloud(){if(loadingCloud||syncing)return;loadingCloud=true;setStatus('Online-Stand wird geladen …');try{const response=await fetch('/api/family-state');if(response.status===401){showLogin('Bitte erneut anmelden.');return}if(!response.ok)throw Error();const remote=await response.json(),known=Number(localStorage.getItem(REVISION)||0),dirty=localStorage.getItem(DIRTY)==='1'||localStorage.getItem('mm-pending-upload');cloudRevision=remote.revision||0;if(dirty&&remote.document&&remote.revision!==known){const keepLocal=confirm('Auf diesem Gerät und online wurden Änderungen vorgenommen.\n\nOK: Änderungen dieses Geräts übernehmen\nAbbrechen: aktuellen Online-Stand laden');if(!keepLocal){applyDocument(remote.document);localStorage.removeItem(DIRTY);localStorage.removeItem('mm-pending-upload');localStorage.setItem(REVISION,String(cloudRevision));setStatus('✓ Online-Stand geladen');return}}if(dirty){localStorage.removeItem('mm-pending-upload');await pushCloud()}else if(remote.document){if(remote.revision!==known)applyDocument(remote.document);localStorage.setItem(REVISION,String(cloudRevision));setStatus('✓ Aktuell')}else{await pushCloud()}}catch{setStatus('Offline – lokaler Stand verfügbar')}finally{loadingCloud=false}}
function $(s,root=document){return root.querySelector(s)}
function esc(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
function render(){renderTabs();renderChildren();const a=stars('max'),b=stars('matilda');$('#family-stars').textContent=a+b;$('#reward-label').textContent=settings.reward||'Noch keine Belohnung eingetragen';$('#goal-label').textContent=`Ziel: jeweils ${settings.target} von 5 Sternen`;$('#goal-status').innerHTML=`<span class="max-dot"></span> Max ${a}/${settings.target}<br><span class="matilda-dot"></span> Matilda ${b}/${settings.target}`;const done=complete('max',selected)&&complete('matilda',selected);$('#celebration').hidden=!done;$('#complete-day').disabled=done}
function renderTabs(){const host=$('#day-tabs');host.replaceChildren();DAYS.forEach((d,i)=>{const b=document.createElement('button');b.type='button';b.className=`day-tab${i===selected?' active':''}${weekday===i+1?' today':''}`;b.setAttribute('aria-pressed',String(i===selected));b.innerHTML=`${d}<span>${complete('max',i)&&complete('matilda',i)?'⭐':'○'}</span>`;b.onclick=()=>{selected=i;render()};host.append(b)})}
function renderChildren(){const host=$('#children');host.replaceChildren();PEOPLE.forEach(person=>{const tasks=relevant(person.id,selected),done=tasks.filter(t=>checked(person.id,selected,t.id)).length,card=document.createElement('section');card.className=`child-card ${person.id}`;card.innerHTML=`<div class="child-head"><div class="identity"><div class="avatar">M</div><div><h2>${person.name}</h2><p class="progress">${FULL[selected]}: ${done} von ${tasks.length}</p></div></div><div class="day-star">${tasks.length&&done===tasks.length?'⭐':''}</div></div><div class="task-list"></div><div class="week-strip"><div class="week-strip-head"><span>${person.pos} Woche</span><span>${stars(person.id)} / 5 ⭐</span></div><div class="mini-week">${DAYS.map((d,i)=>`<div class="mini-day">${d}<span>${complete(person.id,i)?'⭐':'○'}</span></div>`).join('')}</div></div>`;const list=$('.task-list',card);if(!tasks.length)list.innerHTML='<p class="empty-day">Heute sind keine Aufgaben eingetragen.</p>';tasks.forEach(task=>{const value=checked(person.id,selected,task.id),row=document.createElement('div');row.className='task-row';row.innerHTML=`<label class="task${value?' done':''}"><input type="checkbox" ${value?'checked':''}><span class="check">${value?'✓':''}</span><span class="task-icon">${esc(task.emoji)}</span><span class="task-text">${esc(task.label)}</span></label>${task.people.length===2?'<button class="both-button" type="button">Beide</button>':''}`;$('input',row).onchange=e=>{setChecked(person.id,selected,task.id,e.target.checked);save();render()};$('.both-button',row)?.addEventListener('click',()=>{const next=!(checked('max',selected,task.id)&&checked('matilda',selected,task.id));PEOPLE.forEach(p=>{if(relevant(p.id,selected).some(t=>t.id===task.id))setChecked(p.id,selected,task.id,next)});save();render()});list.append(row)});host.append(card)})}
function ask(title,text,label,action,danger=true){$('#confirm-title').textContent=title;$('#confirm-text').textContent=text;const b=$('#confirm-action');b.textContent=label;b.className=danger?'danger':'primary-button';pending=action;$('#confirm-dialog').showModal()}
$('#confirm-dialog').addEventListener('close',e=>{if(e.target.returnValue==='confirm'&&pending)pending();pending=null});
$('#complete-day').onclick=()=>ask('Alles für heute erledigt?',`Alle offenen Aufgaben für ${FULL[selected]} werden bei Max und Matilda abgehakt.`,'Alles erledigt',()=>{PEOPLE.forEach(p=>relevant(p.id,selected).forEach(t=>setChecked(p.id,selected,t.id,true)));save();render()},false);
$('#reset-day').onclick=()=>ask('Tag zurücksetzen?',`Alle Häkchen für ${FULL[selected]} werden entfernt.`,'Zurücksetzen',()=>{PEOPLE.forEach(p=>relevant(p.id,selected).forEach(t=>setChecked(p.id,selected,t.id,false)));save();render()});
$('#history-button').onclick=()=>{renderHistory();$('#history-dialog').showModal()};
function renderHistory(){const weeks=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith(PREFIX)){try{weeks.push({date:key.slice(PREFIX.length),data:JSON.parse(localStorage.getItem(key))})}catch{}}}weeks.sort((a,b)=>b.date.localeCompare(a.date));const host=$('#history-list');host.innerHTML=weeks.length?weeks.map(w=>{const start=new Date(`${w.date}T12:00:00`),end=new Date(start);end.setDate(end.getDate()+4);return`<div class="history-row"><div><strong>${shortDate(start)} – ${shortDate(end)}</strong>${w.date===weekKey?'<small>Aktuelle Woche</small>':''}</div><span class="max-pill">Max ${stars('max',w.data)} ⭐</span><span class="matilda-pill">Matilda ${stars('matilda',w.data)} ⭐</span></div>`}).join(''):'<p class="empty-day">Noch kein Wochenverlauf vorhanden.</p>'}
function shortDate(d){return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'2-digit'}).format(d)}
$('#settings-button').onclick=openSettings;document.querySelectorAll('[data-close-settings]').forEach(b=>b.onclick=()=>$('#settings-dialog').close());
function openSettings(){draft=clone(settings.tasks);$('#reward-input').value=settings.reward;$('#target-input').value=String(settings.target);renderEditor();$('#settings-dialog').showModal()}
function renderEditor(){const host=$('#task-editor');host.replaceChildren();draft.forEach((task,index)=>{const item=document.createElement('div');item.className='task-edit';item.innerHTML=`<div class="task-edit-main"><input class="emoji-input" value="${esc(task.emoji)}" aria-label="Symbol"><input class="label-input" value="${esc(task.label)}" aria-label="Aufgabenname"><button type="button" class="delete-task" aria-label="Löschen">×</button></div><div class="choice-row"><span>Für:</span>${PEOPLE.map(p=>`<label><input type="checkbox" data-person="${p.id}" ${task.people.includes(p.id)?'checked':''}> ${p.name}</label>`).join('')}</div><div class="choice-row"><span>Tage:</span>${DAYS.map((d,i)=>`<label><input type="checkbox" data-day="${i}" ${task.days.includes(i)?'checked':''}> ${d}</label>`).join('')}</div>`;$('.emoji-input',item).oninput=e=>task.emoji=e.target.value.slice(0,4);$('.label-input',item).oninput=e=>task.label=e.target.value;item.querySelectorAll('[data-person]').forEach(c=>c.onchange=()=>task.people=PEOPLE.filter(p=>$(`[data-person="${p.id}"]`,item).checked).map(p=>p.id));item.querySelectorAll('[data-day]').forEach(c=>c.onchange=()=>task.days=DAYS.map((_,i)=>i).filter(i=>$(`[data-day="${i}"]`,item).checked));$('.delete-task',item).onclick=()=>{draft.splice(index,1);renderEditor()};host.append(item)})}
$('#add-task').onclick=()=>{draft.push({id:`task-${Date.now()}`,emoji:'✅',label:'Neue Aufgabe',people:['max','matilda'],days:[0,1,2,3,4]});renderEditor()};
$('#settings-form').onsubmit=e=>{e.preventDefault();const tasks=draft.map(t=>({...t,label:t.label.trim()||'Aufgabe'})).filter(t=>t.people.length&&t.days.length);if(!tasks.length){alert('Mindestens eine Aufgabe muss einem Kind und einem Tag zugeordnet sein.');return}settings={reward:$('#reward-input').value.trim(),target:Number($('#target-input').value),tasks};state.taskSnapshot=clone(tasks);localStorage.setItem(SETTINGS,JSON.stringify(settings));localStorage.setItem(storageKey,JSON.stringify(state));localStorage.setItem(DIRTY,'1');$('#settings-dialog').close();render();setStatus('Wird online gespeichert …');queueCloud()};
$('#export-data').onclick=()=>{const backup={app:'max-matilda-wochenaufgaben',version:2,exported:new Date().toISOString(),settings,weeks:{}};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith(PREFIX))backup.weeks[key]=JSON.parse(localStorage.getItem(key))}const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`wochenaufgaben-sicherung-${dateKey(new Date())}.json`;a.click();URL.revokeObjectURL(url)};
$('#import-data').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const backup=JSON.parse(await file.text());if(backup.app!=='max-matilda-wochenaufgaben'||backup.version!==2)throw Error();ask('Sicherung einlesen?','Der gemeinsame Online-Stand wird durch diese Sicherung ersetzt oder ergänzt.','Einlesen',()=>{localStorage.setItem(SETTINGS,JSON.stringify(backup.settings));Object.entries(backup.weeks||{}).forEach(([k,v])=>localStorage.setItem(k,JSON.stringify(v)));localStorage.setItem(DIRTY,'1');localStorage.setItem('mm-pending-upload','1');location.reload()})}catch{alert('Diese Datei ist keine gültige Sicherung.')}finally{e.target.value=''}};
$('#login-form').onsubmit=async e=>{e.preventDefault();const button=$('.login-submit'),username=$('#login-username').value,password=$('#login-password').value;button.disabled=true;$('#login-error').textContent='';try{const response=await fetch('/api/auth',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password})});const data=await response.json();if(!response.ok){showLogin(data.error||'Anmeldung fehlgeschlagen.');return}$('#login-password').value='';$('#login-dialog').close();setStatus('Angemeldet – lade Online-Stand …');syncFromCloud()}catch{showLogin('Keine Verbindung. Bitte später erneut versuchen.')}finally{button.disabled=false}};
$('#logout-button').onclick=async()=>{await fetch('/api/auth',{method:'DELETE'}).catch(()=>{});$('#settings-dialog').close();showLogin('Erfolgreich abgemeldet.')};
const friday=new Date(monday);friday.setDate(friday.getDate()+4);const fmt=new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'});$('#week-label').textContent=`${fmt.format(monday)} – ${fmt.format(friday)}`;$('#weekend-note').hidden=weekday!==0&&weekday!==6;render();ensureSession();window.addEventListener('online',ensureSession);window.addEventListener('focus',syncFromCloud);document.addEventListener('visibilitychange',()=>{if(!document.hidden)syncFromCloud()});setInterval(()=>{if(!document.hidden)syncFromCloud()},30000);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
})();
